### ISSUE TITLE
AttributeError: module 'tensorflow_core._api.v2.nn' has no attribute 'rnn_cell'

### ISSUE THREAD

**Issue by dusty-dusty** [daniel-kukiela/nmt-chatbot#143]
Python 3.7.4
tensorflow 2.0.0

Traceback (most recent call last):
  File "train.py", line 8, in <module>
    from nmt import nmt
  File "D:\Coding\aichatbot\nmt-chatbot-master/nmt\nmt\nmt.py", line 28, in <module>
    from . import inference
  File "D:\Coding\aichatbot\nmt-chatbot-master/nmt\nmt\inference.py", line 25, in <module>
    from . import gnmt_model
  File "D:\Coding\aichatbot\nmt-chatbot-master/nmt\nmt\gnmt_model.py", line 261, in <module>
    class GNMTAttentionMultiCell(tf.nn.rnn_cell.MultiRNNCell):
AttributeError: module 'tensorflow_core._api.v2.nn' has no attribute 'rnn_cell'

**Comment by dusty-dusty** [comment]
pip install tensorflow-gpu==1.14

solves the issue dont use v2

**Comment by nora-illanes** [comment]
> pip install tensorflow-gpu==1.14

I have the same problem, and it didnt solve it. Im working with tensorflow 2.0 but the code is written in tensorflow 1.7. To rewrite the code is unrealistic. I use v1. compatible for all variables, but I have problems with this issue. How to make it compatible?
